const wmoCodes = {
	0: { en: 'Clear', ru: 'Ясно', uk: 'Ясно' },
	1: { en: 'Mostly Clear', ru: 'В основном ясно', uk: 'Переважно ясно' },
	2: { en: 'Partly Cloudy', ru: 'Частично облачно', uk: 'Частково хмарно' },
	3: { en: 'Cloudy', ru: 'Облачно', uk: 'Хмарно' },
	45: { en: 'Fog', ru: 'Туман', uk: 'Туман' },
	48: { en: 'Freezing Fog', ru: 'Замерзающий туман', uk: 'Замерзаючий туман' },
	51: { en: 'Light Drizzle', ru: 'Легкая морось', uk: 'Легка мряка' },
	53: { en: 'Drizzle', ru: 'Морось', uk: 'Мряка' },
	55: { en: 'Heavy Drizzle', ru: 'Сильная морось', uk: 'Сильна мряка' },
	56: {
		en: 'Light Freezing Drizzle',
		ru: 'Легкая замерзающая морось',
		uk: 'Легка замерзаюча мряка',
	},
	57: { en: 'Freezing Drizzle', ru: 'Замерзающая морось', uk: 'Замерзаюча мряка' },
	61: { en: 'Light Rain', ru: 'Легкий дождь', uk: 'Легкий дощ' },
	63: { en: 'Rain', ru: 'Дождь', uk: 'Дощ' },
	65: { en: 'Heavy Rain', ru: 'Сильный дождь', uk: 'Сильний дощ' },
	66: { en: 'Light Freezing Rain', ru: 'Легкий замерзающий дождь', uk: 'Легкий замерзаючий дощ' },
	67: { en: 'Freezing Rain', ru: 'Замерзающий дождь', uk: 'Замерзаючий дощ' },
	71: { en: 'Light Snow', ru: 'Лёгкий снег', uk: 'Легкий сніг' },
	73: { en: 'Snow', ru: 'Снег', uk: 'Сніг' },
	75: { en: 'Heavy Snow', ru: 'Сильный снег', uk: 'Сильний сніг' },
	77: { en: 'Snow Grains', ru: 'Снежные зерна', uk: 'Сніжні зерна' },
	80: { en: 'Light Rain Shower', ru: 'Легкий ливень', uk: 'Легка злива' },
	81: { en: 'Rain Shower', ru: 'Ливень', uk: 'Злива' },
	82: { en: 'Heavy Rain Shower', ru: 'Сильный ливень', uk: 'Сильна злива' },
	85: { en: 'Snow Shower', ru: 'Снегопад', uk: 'Cнігопад' },
	86: { en: 'Heavy Snow Shower', ru: 'Сильный снегопад', uk: 'Сильнbq cнігопад' },
	95: { en: 'Thunderstorm', ru: 'Гроза', uk: 'Гроза' },
	96: { en: 'Hailstorm', ru: 'Гроза с градом', uk: 'Гроза з градом' },
	99: { en: 'Heavy Hailstorm', ru: 'Сильная гроза с градом', uk: 'Сильна гроза з градом' },
};

export default wmoCodes;
